%% Parameters
env_parameters = struct('NEIGHBOR_THRESHOLD', 0.8, ...
                        'NR_LOC', 0, ...
                        'NR_AGENT', 50, ...
                        'NR_OBFLOC', 100, ...    % 100 
                        'NR_TASK', 1, ...
                        'ALPHA', 100, ...
                        'EPSILON', 5, ...
                        'REGION_SCALE', 20, ... 
                        'NR_NODE_IN_TARGET', 2000, ...   % 300
                        'ITER', 100, ...
                        'obf_loc', [], ...
                        'cost_matrix', []); 

rl_parameters = struct('discount', 0.50, ...
                        'alpha', 0.02, ...
                        'NR_EPISODE', 100); 

